### ISSUE TITLE
Cards are empty (properties not rendered ?)

### ISSUE THREAD

**Issue by stockersky** [HusamFathi/KivyMD-Dashboard-UI#1]
Thanks for this example. 
I found it through Youtube and cloned this repo as a first contact with Kivy/KivyMD (after doing the Pong exemple :)).

However, when executing the code from commit (03f660194b282195d2d2a4a775ff4689e6393cdb), i get the following screen : 

It looks like Cards do not get their properties...

<img width="800" alt="image" src="https://user-images.githubusercontent.com/22478549/189763360-f39f7881-0e42-4f14-bdd5-1e22bc163c46.png">

**Comment by stockersky** [comment]
I could make it work with those changes:

In main.py, I declared the properties of `ElementCard` in its own class:

```Python
class ElementCard(MDCard):
    text = StringProperty()
    image = StringProperty()
    items_count = StringProperty()
    subtext = StringProperty()
```

in `main.kv`, as it's already done just above, I removed the inheritance from `MDCard` and  also the properties declaration :

```kv
<ElementCard>:
    md_bg_color:69/255,55/255,86/255,1
    padding:dp(15)
    spacing:dp(15)
    radius:dp(25)
    ripple_behavior: True
    
    orientation:'vertical'
    Image:
        source:root.image
    MDBoxLayout:
.........
.........
```

**Comment by besnoi** [comment]
i believe this has something to do with the version of kivymd you are using

try downgrading to 0.104.2

> pip install kivymd==0.104.2

**Comment by HusamFathi** [comment]
use `kivymd==0.104.2`
